### ISSUE TITLE
paper spigot 1.14.4 SkungeePingEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by ham1255** [Skungee/Skungee#70]
```
>.... [05:27:52 WARN]: Exception in thread "Thread-406" java.lang.IllegalStateException: SkungeePingEvent may only be triggered synchronously.
>.... [05:27:52 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
>.... [05:27:52 WARN]: at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.handlePacket(SpigotPacketHandler.java:195)
>.... [05:27:52 WARN]: at me.limeglass.skungee.spigot.sockets.SpigotRunnable.run(SpigotRunnable.java:85)
>.... [05:27:52 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by ham1255** [comment]
same problem apply in every event
```
SkungeePlayerSwitchServer may only be triggered synchronously
```

**Comment by Romitou** [comment]
Hello!
I also have the same errors in the console. ;)

`[15:34:06] [Thread-13/WARN]: Exception in thread "Thread-13" java.lang.IllegalStateException: SkungeePingEvent may only be triggered synchronously.`

`[15:34:17] [Thread-15/WARN]: Exception in thread "Thread-15" java.lang.IllegalStateException: SkungeePlayerSwitchServer may only be triggered synchronously.`

`[15:34:28] [Thread-16/WARN]: Exception in thread "Thread-16" java.lang.IllegalStateException: SkungeePlayerCommandEvent may only be triggered synchronously.`

This is probably due to 1.14? ^^

**Comment by ham1255** [comment]
i think somehow paper spigot 1.14 disable async because i noticed when sending a skungee message bungeecord crashes

**Comment by TheLimeGlass** [comment]
Duplicate #63
